import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-primary": "#ffffff",
        "primary-fixed": "#d0e4ff",
        "outline-variant": "#c1c7d0",
        "inverse-surface": "#303030",
        "secondary-container": "#aeeecb",
        "on-tertiary-fixed": "#1c1c11",
        secondary: "#2c694e",
        outline: "#727780",
        "on-surface-variant": "#42474f",
        "on-secondary": "#ffffff",
        error: "#ba1a1a",
        "secondary-fixed-dim": "#95d4b3",
        "surface-dim": "#dcd9d9",
        "on-primary-fixed": "#001d35",
        "inverse-on-surface": "#f3f0f0",
        "on-primary-container": "#87baf3",
        "on-error-container": "#93000a",
        "on-tertiary-container": "#b9b7a5",
        "on-background": "#1b1c1c",
        "on-secondary-fixed-variant": "#0e5138",
        "surface-container-low": "#f6f3f2",
        "surface-container": "#f0eded",
        "on-tertiary-fixed-variant": "#48473a",
        "error-container": "#ffdad6",
        "primary-container": "#004a7c",
        tertiary: "#323225",
        "surface-container-highest": "#e4e2e1",
        "on-secondary-container": "#316e52",
        "tertiary-container": "#49483a",
        "on-primary-fixed-variant": "#00497b",
        "inverse-primary": "#9ccaff",
        "primary-fixed-dim": "#9ccaff",
        "secondary-fixed": "#b1f0ce",
        "on-surface": "#1b1c1c",
        surface: "#fbf9f8",
        "surface-variant": "#e4e2e1",
        "tertiary-fixed-dim": "#c9c7b5",
        background: "#fbf9f8",
        primary: "#003358",
        "on-secondary-fixed": "#002114",
        "surface-container-lowest": "#ffffff",
        "surface-container-high": "#eae8e7",
        "on-tertiary": "#ffffff",
        "surface-bright": "#fbf9f8",
        "tertiary-fixed": "#e6e3d0",
        "surface-tint": "#296195",
        "on-error": "#ffffff",
      },
      borderRadius: {
        sm: "0.125rem",
        DEFAULT: "0.25rem",
        md: "0.375rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "container-max": "1280px",
        unit: "8px",
        gutter: "24px",
        "margin-mobile": "20px",
        "margin-desktop": "64px",
      },
      maxWidth: {
        "container-max": "1280px",
      },
      fontFamily: {
        "headline-xl": ["var(--font-public-sans)"],
        "headline-lg-mobile": ["var(--font-public-sans)"],
        caption: ["var(--font-public-sans)"],
        "body-lg": ["var(--font-public-sans)"],
        "headline-md": ["var(--font-public-sans)"],
        "body-md": ["var(--font-public-sans)"],
        "label-md": ["var(--font-public-sans)"],
        "headline-lg": ["var(--font-public-sans)"],
        sans: ["var(--font-public-sans)"],
      },
      fontSize: {
        "headline-xl": [
          "48px",
          { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "headline-lg-mobile": [
          "28px",
          { lineHeight: "36px", fontWeight: "700" },
        ],
        caption: ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-md": [
          "14px",
          { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "600" },
        ],
        "headline-lg": [
          "32px",
          { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" },
        ],
      },
    },
  },
  plugins: [],
};

export default config;
